### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by algorithmiker** [arvidj/poemizer#1]
Hey!
I was planning to re-implement this ancient project of yours in Flutter as a coding exercise. I don't know if you made this by yourself, but if so, could you release it under an open-source license so I can include it in my project?

Thanks.

**Comment by arvidj** [comment]
Sure, what do you actually require? That I add a LICENCE file to the repository?

**Comment by algorithmiker** [comment]
Yep, that would be wonderful, any permissive license (eg from https://choosealicense.com) works fine. Thanks for replying!

**Comment by arvidj** [comment]
There, I used the MIT license. Does that work?

**Comment by arvidj** [comment]
https://github.com/arvidj/poemizer/commit/28201d5a2f077d1291e55917599302b0c3098b6e

**Comment by algorithmiker** [comment]
yep! thanks a lot!

**Comment by gilice** [comment]
Yep please! Any permissive license from https://choosealicense.com would be
fine.
